name: reddit_tutorial
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # For Firebase
  firebase_core: ^2.24.2
  firebase_storage: ^11.5.5
  cloud_firestore: ^4.13.5
  firebase_auth: ^4.15.2

  # For Sign In
  google_sign_in: ^6.1.6

  # For State Management
  flutter_riverpod: ^2.4.9

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
