name: reddit_tutorial
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # For Error Handling
  fpdart: ^1.1.0

  # For Firebase
  firebase_core: ^2.24.2
  firebase_storage: ^11.5.5
  cloud_firestore: ^4.13.5
  firebase_auth: ^4.15.2

  # For Generate unique ID
  uuid: ^4.2.2

  # For Route Management
  routemaster: ^1.0.1

  # For Sign In
  google_sign_in: ^6.1.6

  # For State Management
  flutter_riverpod: ^2.4.9

  # For store data in secure storage
  shared_preferences: ^2.2.2

  # For UI
  any_link_preview: ^3.0.1
  dotted_border: ^2.1.0
  file_picker: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/awards/

  fonts:
    - family: MyFlutterApp
      fonts:
        - asset: assets/fonts/MyFlutterApp.ttf
