// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8zMzQ2lHdfyu0Iym3yEOPfXzGj5ZJ6w0',
    appId: '1:121795108150:web:02845774250713e9cfe797',
    messagingSenderId: '121795108150',
    projectId: 'reddit-clone-tutorial-e9d5b',
    authDomain: 'reddit-clone-tutorial-e9d5b.firebaseapp.com',
    storageBucket: 'reddit-clone-tutorial-e9d5b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABftNkIo2g9gzBl8qtR1SRDq2ydv5bSXA',
    appId: '1:121795108150:android:bdf4cf16594f81bacfe797',
    messagingSenderId: '121795108150',
    projectId: 'reddit-clone-tutorial-e9d5b',
    storageBucket: 'reddit-clone-tutorial-e9d5b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDi7fttch-osQaPrCKEY7rJRlBzvR6QARs',
    appId: '1:121795108150:ios:68f61d25296922e1cfe797',
    messagingSenderId: '121795108150',
    projectId: 'reddit-clone-tutorial-e9d5b',
    storageBucket: 'reddit-clone-tutorial-e9d5b.appspot.com',
    iosBundleId: 'com.example.redditTutorial',
  );
}
