// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGn8fuiwtNaQBowlAEnOvs5gq3wegyCmU',
    appId: '1:50255608182:web:dc2356fbaf7eb087a7e257',
    messagingSenderId: '50255608182',
    projectId: 'reddit-clone-tutorial-34cf2',
    authDomain: 'reddit-clone-tutorial-34cf2.firebaseapp.com',
    storageBucket: 'reddit-clone-tutorial-34cf2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcskJr9EWmIs461qGixwsIMBGDWJzBzHU',
    appId: '1:50255608182:android:6f0dc7d8d4028b22a7e257',
    messagingSenderId: '50255608182',
    projectId: 'reddit-clone-tutorial-34cf2',
    storageBucket: 'reddit-clone-tutorial-34cf2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBET8UnJWJ61pRnnaEyaZsen1Zqc39pV2U',
    appId: '1:50255608182:ios:001c3a71cbefa70ea7e257',
    messagingSenderId: '50255608182',
    projectId: 'reddit-clone-tutorial-34cf2',
    storageBucket: 'reddit-clone-tutorial-34cf2.appspot.com',
    iosBundleId: 'com.example.redditTutorial',
  );
}
